### ISSUE TITLE
about SMPL-X

### ISSUE THREAD

**Issue by i-dont-know-how-to-sign-up** [bytedance/OHTA#1]
Thanks for your great work.
When I tried to run create.py,  I encountered a problem:

 File "core/nets/ohta/network.py", line 15, in <module>
    from third_parties.smplx.manohd.subdivide import sub_mano
ModuleNotFoundError: No module named 'third_parties.smplx.manohd'

Then I check core/nets/ohta/network.py,:

import third_parties.smplx
from third_parties.smplx.manohd.subdivide import sub_mano
from third_parties.smplx.utils import vertex_normals
from third_parties.smplx.lbs import get_normal_coord_system
from third_parties.pairof.pairof_model import attach_pairof

I couldn't find the sub-files of SMPLX, so I can't run the 'create.py' script. Where can I find these sub-files of SMPLX?

**Comment by i-dont-know-how-to-sign-up** [comment]
I have check this link :https://github.com/vchoutas/smplx/tree/main/smplx
However, these is no 'manohd' , so I am not sure what should be included in the smplx directory.

**Comment by walsvid** [comment]
Hi @i-dont-know-how-to-sign-up. As described in the README under the MANO-HD section, I suggest that you refer to the code at [https://github.com/SeanChenxy/HandAvatar](https://github.com/SeanChenxy/HandAvatar), where there is an implementation of manohd.
